logstashJavaOpts: "-Xmx1g -Xms1g"
resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
persistence:
  enabled: True
extraPorts:
  - name: beats
    containerPort: 5044
service:
  type: NodePort
  ports:
    - name: syslog
      port: 5140
      protocol: UDP
      nodePort: 31514
    - name: beats
      port: 5044
      protocol: TCP
      nodePort: 30544
logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
logstashPipeline:
  logstash.conf: |
    input {
      syslog {
        port => 5140
        add_field => { "[@metadata][input_id]" => "syslog_input" }
      }
      beats {
        port => 5044
        add_field => { "[@metadata][input_id]" => "beats_input" }
      }
    }

    filter {
      if [@metadata][input_id] == "syslog_input" {
        mutate {
          replace => { "[@metadata][index_prefix]" => "syslog" }
        }

        grok {
          match => {
            "message" => "%{SYSLOG5424LINE}"
          }
          overwrite => [ "message" ]
          tag_on_failure => ["syslog_parse_failed"]
        }

        if "syslog_parse_failed" in [tags] {
          grok {
            match => {
              "message" => "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_host} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}"
            }
            overwrite => [ "message" ]
            remove_tag => ["syslog_parse_failed"]
            tag_on_failure => ["syslog_rfc3164_failed"]
          }
        }

        date {
          match => [ "syslog_timestamp", "ISO8601", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
          target => "@timestamp"
        }
      }
      else if [@metadata][input_id] == "beats_input" {
        if "weblog" in [tags] {
          mutate {
            replace => { "[@metadata][index_prefix]" => "weblog" }
          }

          grok {
            match => { "message" => "%{HTTPD_COMBINEDLOG}" }
            overwrite => [ "message" ]
            tag_on_failure => ["weblog_parse_failed"]
          }

          date {
            match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
            target => "@timestamp"
          }

          if "access_log" in [tags] {
            dissect {
              mapping => {
                "[log][file][path]" => "%{path}/access.%{domain}.log.1"
              }
            }
          }
          if "error_log" in [tags] {
            dissect {
              mapping => {
                "[log][file][path]" => "%{path}/error.%{domain}.log.1"
              }
            }
          }
        }
        else if "c0a22069-log-collector-2" in [tags] {
          grok{
            match => {
          "message" => '\[%{TIMESTAMP_ISO8601:log_time}\] "%{WORD:method} %{DATA:uri} HTTP/%{NUMBER:http_version}" %{NUMBER:status_code:int} %{GREEDYDATA:rest}'
            }
            tag_on_failure => [istio_http_parse]
          }
          mutate {
            replace => { "[@metadata][index_prefix]" => "doktor-istio" }
          }
        }
        else {
          mutate {
            replace => { "[@metadata][index_prefix]" => "beats" }
          }
        }
      }
      else {
        mutate {
          add_field => { "[@metadata][index_prefix]" => "default" }
        }
      }
    }

    output {
      # stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "%{[@metadata][index_prefix]}-%{+YYYY.MM.dd}"
      }
      }
